USE ExamDB;
GO
DROP SCHEMA IF EXISTS Exam;
GO
CREATE SCHEMA Exam;
GO
DROP PROCEDURE IF EXISTS Exam.Proc1
GO
CREATE PROCEDURE Exam.Proc1
AS
SELECT 1;

--1
CREATE LOGIN [NewExamLogin] WITH PASSWORD=N'asd123!' MUST_CHANGE, DEFAULT_DATABASE=[ExamDB], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
--2
CREATE USER [NewExamUser] FOR LOGIN [NewExamLogin]
GO
--3
CREATE ROLE [Exam Admins]
GO
--4
CREATE ROLE [Exam Contributors]
GO
--5
ALTER ROLE [Exam Admins] ADD MEMBER [NewExamUser]
GO
--6
GRANT EXECUTE ON SCHEMA::[Exam] TO [Exam Admins]
GO
--7
DENY EXECUTE ON SCHEMA::[Exam] TO [Exam Contributors]
GO

--8+9
EXECUTE AS USER = [NewExamUser];
GO
EXECUTE [Exam].Proc1; 
REVERT;
GO

--10
SELECT CURRENT_USER;  
GO  

SELECT SYSTEM_USER;  
GO