SELECT SERVERPROPERTY('EditionId') AS EditionId
GO
SELECT SERVERPROPERTY('IsXTPSupported')
GO
SELECT SERVERPROPERTY('IsXTPSupported')
GO
USE [master]
GO
ALTER DATABASE [WideWorldImporters] 
SET RECOVERY FULL WITH NO_WAIT
GO

